# Generated by Django 3.0.6 on 2020-05-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplugin',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='_eventplugin_events_+', related_query_name='+', to='events.Event', verbose_name='events'),
        ),
        migrations.AddField(
            model_name='eventplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_eventplugin_set', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='button',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_button_set', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='articleplugin',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='blog_articleplugin', to='blog.Article', verbose_name='articles'),
        ),
        migrations.AddField(
            model_name='articleplugin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='articleplugin',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Namespace', verbose_name='namespace'),
        ),
        migrations.AddField(
            model_name='articleplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articleplugin_set', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='article',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Namespace', verbose_name='namespace'),
        ),
    ]
